---
abstract: 'Keep imports and functions out of your namespace'
author:
  - "Robert 'phaylon' Sedlacek <rs@474.at>, Florian Ragwitz <rafl@debian.org>, Jesse Luehrs <doy@tozt.net>"
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::CBuilder: 0.27
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: namespace-clean
no_index:
  directory:
    - t
    - inc
requires:
  B::Hooks::EndOfScope: 0.12
  Package::Stash: 0.23
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=namespace-clean
  homepage: http://search.cpan.org/dist/namespace-clean
  repository: git://git.shadowcat.co.uk/p5sagit/namespace-clean.git
version: 0.25
